
package com.epam.webservices.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.epam.webservices.ObjectFactory;
import com.epam.webservices.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://webservices.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.epam.com/HelloService/getSimpleRequest", output = "http://webservices.epam.com/HelloService/getSimpleResponse")
    public String getSimple();

    /**
     * 
     * @param user
     * @return
     *     returns com.epam.webservices.User
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.epam.com/HelloService/saveUserRequest", output = "http://webservices.epam.com/HelloService/saveUserResponse")
    public User saveUser(
        @WebParam(name = "user", partName = "user")
        User user);

    /**
     * 
     * @param num
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.epam.com/HelloService/getNumRequest", output = "http://webservices.epam.com/HelloService/getNumResponse")
    public String getNum(
        @WebParam(name = "num", partName = "num")
        int num);

}
